[FEATURE] - Expose REST API to Generate a Yaml Schema from an Excel file
ebiznext/comet-data-pipeline pull request #387
Opened 2020-11-24 09:07 UTC by AmineSagaama

## Summary
The purpose of this feature is to implement a REST API based application, aimed at generating a Yaml schema
from an Excel file.
As a first step, the REST API, will expose two endpoints, one for generating a simple Yaml schema from an excel file,
and the other, for generating a Yaml schema in case of Encrypt/Decrypt Columns for PII, GDPR Compliance..

**Related Issue: #386**

**PR Type: Feature**

**Status: Ready to review**

**Breaking change? No**

## Contributor checklist:
Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-12-02 15:12 UTC, AmineSagaama commented
Reopen Merge Request, after merge from master to dev/comet_service

2020-12-02 19:10 UTC, hayssams requested changes

2020-12-02 19:10 UTC, hayssams commented on build.sbt
> -        (spark_3d0_forScala_2d12, jackson312)
We already talked about this before
Would be good if you keep spark an external dependency and loaded into the docker image

2020-12-03 21:01 UTC, hayssams approved these changes

2020-12-03 21:01 UTC, merged