WIP: Save rejected input for later replay
ebiznext/comet-data-pipeline pull request #550
Opened 2021-06-21 07:58 UTC by hayssams

## Summary
Rejected lines may be now saved in the replay area with the filename domain.schema.yyyyMMddHHmmss.replay
This is controlled by the boolean setting 'sink-replay-to-file'

**PR Type: Feature**

**Status: WIP**

**Breaking change? No**

2021-06-28 12:25 UTC, mhdkassir requested changes
I left some comments/questions

2021-06-28 12:25 UTC, mhdkassir commented on src/main/scala/com/ebiznext/comet/job/ingest/IngestionJob.scala
> +    } else {
What happens in this case , we won't write anything in accepted zone but the ingestion is yet successful ?

2021-06-28 12:25 UTC, mhdkassir commented on src/main/scala/com/ebiznext/comet/job/ingest/XmlSimplePrivacyJob.scala
> +      case _ =>
I don't this will work since we read the xml file as a text file (line by line)

2021-06-28 12:25 UTC, mhdkassir commented on src/main/scala/com/ebiznext/comet/schema/model/Rejection.scala
> +    inputLine: String
inputLine shoud only be used for replay file

2021-06-28 12:25 UTC, mhdkassir commented on src/main/scala/com/ebiznext/comet/schema/model/Rejection.scala
> +      s"""$colName: $typeName("$pattern") = "$colData" ? $failMsg"""
why change the comma-separated format

2021-06-28 12:41 UTC, hayssams commented on src/main/resources/reference.conf
> +reject-all-on-error = false
Done

2021-06-28 12:48 UTC, hayssams commented on src/main/scala/com/ebiznext/comet/job/ingest/IngestionJob.scala
> +    } else {
The Audit log will now mark the job as failed on error.

2021-06-28 12:52 UTC, hayssams commented on src/main/scala/com/ebiznext/comet/job/ingest/XmlSimplePrivacyJob.scala
> +      case _ =>
reverted

2021-06-29 08:06 UTC, mhdkassir commented on src/main/scala/com/ebiznext/comet/job/validator/FlatRowValidator.scala
> +  private def toOriginalFormat(row: Row, format: Format, separator: String): String = {
the output String contains the comet_input_file_name , can we have an output line without the filename ?

2021-06-29 13:17 UTC, hayssams commented on src/main/scala/com/ebiznext/comet/job/validator/FlatRowValidator.scala
> +  private def toOriginalFormat(row: Row, format: Format, separator: String): String = {
done

2021-06-29 13:21 UTC, mhdkassir commented on src/main/scala/com/ebiznext/comet/job/ingest/IngestionJob.scala
> +    if (settings.comet.sinkReplayToFile) {
check if the rejectedLinesRDD is empty to avoid writing an empty replay files

2021-06-29 21:42 UTC, mhdkassir commented on src/main/scala/com/ebiznext/comet/job/ingest/IngestionJob.scala
> +    if (settings.comet.sinkReplayToFile) {
check if rejectedLines RDD is empty to avoid writing empty replay files

2021-07-02 10:45 UTC, mhdkassir approved these changes
Tests are OK on GCP

2021-07-02 10:45 UTC, merged