Merge two datasets with different schemas
ebiznext/comet-data-pipeline pull request #601
Opened 2021-09-09 17:45 UTC by seyguai

**Related Issue: #582**

**PR Type: Feature**

**Status: Ready to review**

**Breaking change? No**

## Description
### Solution
- check if schemas are compatible for merge (new schema contains at least all the columns from existing one, and new columns are nullable)
- produce a schema that is built from the new schema, but compatible with the existing one, in order to load the existing data without errors
- expand the existing data with new columns without any value
- do the union with the incoming data
- remove duplicated lines

### How has this been tested?
New Integration test, new unit tests

### Other changes
Rework common algorithm, split into Util class (out of IngestionJob), to simplify testing

## Contributor checklist:
Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [x] I have updated the Release notes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-09-10 11:17 UTC, hayssams requested changes
Great PR
However detailed error reporting is missing in case of incompatible schemas. It would be nice to add it by including what has been done in the following PR bug fix/merge-bq.

2021-09-10 11:17 UTC, hayssams commented on src/main/scala/com/ebiznext/comet/utils/MergeUtils.scala
> +                  col(colName).withField(tail.mkString("."), lit(null).cast(dataType))
Not sure this cover all cases on deep column match

2021-09-10 11:59 UTC, seyguai commented on src/main/java/com/ebiznext/comet/utils/repackaged/BigQuerySchemaConverters.java
>  import com.google.cloud.bigquery.Field;
Why was this duplicated then ?
I updated the content based on com.google.cloud.spark.bigquery.SchemaConverters sources for v0.22.0, which fixed the bug I had wrongly fixed (not using "comment" to store metadata descriptions)
I kept fix for Timestamp legacy type.

2021-09-10 12:03 UTC, seyguai commented on src/main/scala/com/ebiznext/comet/utils/MergeUtils.scala
> +                  col(colName).withField(tail.mkString("."), lit(null).cast(dataType))
I'm pretty sure this only works since Spark 3.1.1

2021-09-10 12:28 UTC, hayssams commented on src/main/java/com/ebiznext/comet/utils/repackaged/BigQuerySchemaConverters.java
>  import com.google.cloud.bigquery.Field;
I can't remember but this has to be done this way.
I'll look at the commit comments and get back to you

2021-09-10 12:29 UTC, hayssams commented on src/main/scala/com/ebiznext/comet/utils/MergeUtils.scala
> +                  col(colName).withField(tail.mkString("."), lit(null).cast(dataType))
Probably we should make it available for spark 2 by duplicating its implementation somewhere is the repackaged section
what do you think ?

2021-09-10 14:48 UTC, hayssams commented
@seyguai 
This fails on BigQuery (SchemaUpdate not allowed on WRITE_TRUNCATE). Please check how we have to inject session settings in bugfix/bq-merge 
```
 override def extraSparkConf(): Map[String, String] =
     if (cliConfig.writeDisposition == "WRITE_TRUNCATE")
       cliConfig.options ++ Map(
         "spark.datasource.bigquery.allowFieldAddition"   -> "false",
         "spark.datasource.bigquery.allowFieldRelaxation" -> "false"
       )
     else
       cliConfig.options
```

2021-09-13 10:29 UTC, seyguai commented on src/main/scala/com/ebiznext/comet/utils/MergeUtils.scala
> +                  col(colName).withField(tail.mkString("."), lit(null).cast(dataType))
Without any proper way to test properly & maintain any duplicated code, i would rather not do that.
I used [this article](https://medium.com/@fqaiser94/manipulating-nested-data-just-got-easier-in-apache-spark-3-1-1-f88bc9003827) to provide another code that would work with Spark < 3.1.0

2021-09-13 10:32 UTC, hayssams approved these changes
LGTM

2021-09-13 10:37 UTC, merged